services:
  - type: web
    name: prime-heritage-bank-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://mrdev:dev091339@cluster0.grjlq7v.mongodb.net/prime_heritage_bank?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: PrimeHeritageBank_SuperSecure_JWT_2026_Global_International_Banking_System
      - key: SESSION_SECRET
        value: PrimeHeritage_Session_Secret_For_Secure_Banking_Platform_2026
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        value: primeheritageinternationalbank@gmail.com
      - key: EMAIL_PASS
        value: lhjb tgjo jwik gssq
      - key: ADMIN_EMAIL
        value: devgift@gmail.com
      - key: ADMIN_PASSWORD
        value: devgift
      - key: BANK_NAME
        value: Prime Heritage Bank
      - key: BANK_SWIFT
        value: PHBKGLOBAL
      - key: SUPPORT_EMAIL
        value: primeheritageinternationalbank@gmail.com
