services:
  - type: web
    name: prime-heritage-bank
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        value: https://locubftytnfyxacfberj.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_AsPMmqBAtex3C_zfofY8sw_GGJ_nxyk
      - key: GMAIL_USER
        value: primeheritageinternationalbank@gmail.com
      - key: GMAIL_APP_PASSWORD
        value: pzxw dqxj queu wcch
